=== DataIntegrationNJU/DataIntegration/src/main/resources/static/tempCXml/course.xsd
<?xml version="1.0" encoding="gb2312"?>

<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
           targetNamespace="http://www.w3schools.com"
           xmlns="http://www.w3schools.com"
           elementFormDefault="qualified">

    <xs:element name="Cno">
        <xs:simpleType>
            <xs:restriction base="xs:string" />
        </xs:simpleType>
    </xs:element>

    <xs:element name="Cnm">
        <xs:simpleType>
            <xs:restriction base="xs:string" />
        </xs:simpleType>
    </xs:element>

    <xs:element name="Cpt">
        <xs:simpleType >
            <xs:restriction base="xs:integer" />
        </xs:simpleType>
    </xs:element>

    <xs:element name="Tec">
        <xs:simpleType>
            <xs:restriction base="xs:string" />
        </xs:simpleType>
    </xs:element>

    <xs:element name="Pla">
        <xs:simpleType>
            <xs:restriction base="xs:string" />
        </xs:simpleType>
    </xs:element>


    <xs:element name="course">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="Cno" />
                <xs:element ref="Cnm" />
                <xs:element ref="Cpt" />
                <xs:element ref="Tec"/>
                <xs:element ref="Pla"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>


    <xs:element name="courses">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="course" maxOccurs="unbounded"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>

</xs:schema>

=== DataIntegrationNJU/DataIntegration/src/main/resources/static/tempCXml/course.xml
<?xml version="1.0" encoding="gb2312"?>

<courses xmlns="http://www.w3schools.com"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://www.w3schools.com course.xsd">
    <course>
        <Cno>0B01</Cno>
        <Cnm>古建筑鉴定分析学</Cnm>
        <Cpt>2</Cpt>
        <Tec>季勇</Tec>
        <Pla>北教302</Pla>
    </course>

    <course>
        <Cno>0B03</Cno>
        <Cnm>古建筑鉴定分析学</Cnm>
        <Cpt>3</Cpt>
        <Tec>黄建秋</Tec>
        <Pla>南教302</Pla>
    </course>

    <course>
        <Cno>0B07</Cno>
        <Cnm>古建筑鉴定分析学</Cnm>
        <Cpt>2</Cpt>
        <Tec>贺云翱</Tec>
        <Pla>北教102</Pla>
    </course>
</courses>
